Enhanced data  schema for Cloud-native Workload Vulnerability Data Storage for Analytics, Reporting and Policy Evaluation.
goharbor/community pull request #145
Opened 2020-06-24 09:55 UTC by prahaladdarkin

This proposal will lay the foundational work that allow advanced reporting, analytics, policy evaluation and integration with third-party systems providing these capabilities such as Open Policy Agent.
The contents of this proposal are based on the document describing the Cloud Native Workload - Common Vulnerability Evaluation and Reporting Framework.

2020-06-24 16:54 UTC, reasonerjt commented on proposals/new/common_vulnerability_schema_proposal.md
> +type VulnerabilityRecord struct {
There may be duplicated records with same CVE ID, only different ID and report_uuid.

2020-07-01 11:31 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +type VulnerabilityRecord struct {
I have modified the schema to include a junction table that will store the relation between the Vulnerability Records and the reports. Please take a look. 
I would want to know whether ReportUUID would be a good foreign key in the junction table or should it be the auto-generated ID.

2020-07-01 22:08 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +`select count(1) from vulnerability_record where CVEID = '<CVE_ID>'`
It's tempting to have a UI for admins to search for packages with the specified vulnerability. Do we plan to leverage the proposed schema to immediately add simple search / reporting capabilities to the Harbor interface?

2020-07-03 02:46 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +|CVE_3_Score| The score in the CVSS 3.0 format that can be associated with the image|
Excellent comment and queries related to CVSS.
Right now this column represents the overall Qualitative score across all vectors. Given the related comment about CVSS vectors being part of the schema, it would probably make sense to do the following:
* This table maintains the overall qualitative score of the image CVSS2 or CVSS3. 
* A CVSS 3.0 detail schema table can be created where-in we store the data about the attack vectors and also the CIA score for each. 
* Store a reference to the CVSS detail schema rows within this table. This can be null to accommodate scanners that do not provide this information.

Additionally, do we need to worry about CVSS 2.0? As far as I understand this standard is slowly being phased out in favor of CVSS 3.0 which provides more standardized results. In the original document to Liz Rice had commented about the aspect of considering only CVSS 3.0. I am not sure if the default Claire scanner provides CVSS 3.0 score.

2020-07-03 02:46 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +The scan report produced vulnerability scanners in Harbor are stored within a JSON blob within the Harbor DB. This prevents ad-hoc querying of the vulnerability data to provide more richer reporting
Done

2020-07-03 02:53 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +	Fix              string   `orm:"column(fixed_version)"`
Added. I have also provided an example in the attached document in response to the comments related to package version. 
An additional comment I added and require views on is whether the PackageType (OS/SoftwareLib) be actually deduced by the scanner. While I did introduce the field in the original document, in retrospect I do see that the field is redundant and does not provide any valuable information.

2020-07-03 02:55 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +`select count(1) from vulnerability_record where CVEID = '<CVE_ID>'`
@xaleeks  and @steven-zou  can comment. IMO the immediate advantage of this schema should be leveraged. A set of pre-canned reports that satisfy the most pressing reporting use cases can be shipped with Harbor.

2020-07-08 03:28 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +* [Cloud Native Workload - Common Vulnerability Evaluation and Reporting Framework](#)
Attached. Had originally sent it over email

2020-07-08 03:28 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +|CVE_3_Score| The score in the CVSS 3.0 format that can be associated with the image|
@danielpacak  I have introduced CVSS related schema definitions now as a response to this comment. Please take a look

2020-07-08 03:33 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +	VulnRecord int64  `orm:"column(vuln_record_id)`
Currently, I observed that two scans for the same image digests generate different scan report UUIDs. IMO the vulnerability record should have a version field which would be updated each time there is an update to the data from the upstream database. The table here would have a composite key of Report, VulnRecord and VulnRecordVersion to ensure that the historical versions of the vulnerability are preserved and hence all the immutability of the historical scan reports. 
This will however increase storage space for the same vulnerability. How often do vulnerability definitions change?

2020-07-15 02:24 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +	Fix              string   `orm:"column(fixed_version)"`
Discussed with @danielpacak. Will retain the `PackageVersion` field.

2020-07-15 02:28 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +	VulnRecord int64  `orm:"column(vuln_record_id)`
@danielpacak  As discussed during our slack conversation, IMO for any scanner it is  the latest and greatest version of the CVE should be reflected across all reports to avoid ambiguity. It is better to be safe by raising flags to the user indicating that the vulnerability existed historically so that they can take corrective measures or validate any impact in retrospect. 
Additionally, I have now introduced a field for identifying the scanner within the CVE table. In this way each CVE is qualified by the CVE ID and the Scanner ID and hence would be unambiguous if multiple scanners are registered for a project or in the repository

2020-07-20 14:12 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +### Create VulnerabilityReport data structure mapped to vulnerability_data table
```suggestion
### Create VulnerabilityRecord data structure mapped to vulnerability_record table
```

2020-07-20 14:18 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +	Report           string   `orm:"column(report_uuid)"`
Do we need the the `report_uuid` FK? Below you proposed a junction table, so if that's the case this would be redundant.

2020-07-20 14:18 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +	ScannerID		 string   `orm:"unique;column(registration_uuid)"`
Maybe we should call it RegistrationUUID? It's the same value as we expect to be sent as the value of the Report.RegistrationUUID property, isn't it?

2020-07-20 14:24 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +type ReportVulnerability struct {
Not sure if I understood this one. Is this a junction structure to associate a `Report` with zero to many `VulnerabilityRecords`? If yes, we may call it `ReportToVulnerabilityRecord` and prefix FK properties with `ReportID` and `VulnerabilityRecordID`?

2020-07-20 14:35 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +type CVSS3Vector struct {
I'm not terribly sure if we should structure CVSS vectors as a first class relation in RDB model. At least not in the first iteration. Maybe it's good enough to start with properties / columns in the VulnerabilityRecord / vulnerability_record?

```go
type VulnerabilityRecord struct {
	// ...

	CVSS3Vector string // e.g. CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
	CVSS2Vector string // e.g. AV:L/AC:M/Au:N/C:P/I:N/A:N
}
```

2020-08-17 08:54 UTC, danielpacak submitted a review, later dismissed
LGTM

2020-08-27 07:24 UTC, steven-zou commented on proposals/new/common_vulnerability_schema_proposal.md
> +Additionally, Garbage collection process may have to be modified to clean up vulnerability data for garbage collected images
Maybe not handled by GC, just clean the vuln data when deleting the specified images.

2020-08-27 07:25 UTC, steven-zou submitted a review, later dismissed
LGTM

@prahaladdarkin 

I think this is the right way to handle the vuln data. With this schema refactor, it's very friendly to do ad-hoc query that is a feature we're planning to support later.

2020-08-27 07:28 UTC, steven-zou commented on proposals/new/common_vulnerability_schema_proposal.md
> +type VulnerabilityRecord struct {
@danielpacak 

Is it a common way for kinds of scanners to return the concrete image layer info that contains the found vulnerabilities? If I'm not mistaken, Clair has such info. What about Trivy and Aqua CSP?


cc @prahaladdarkin

2020-08-27 08:07 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +type VulnerabilityRecord struct {
In general we should consider LayerID (and LayerDigest) optional properties because not every pluggable scanner might support it. For Trivy and Aqua CSP we do return LayerID.

2020-08-27 09:19 UTC, prahaladdarkin commented
@danielpacak  and @steven-zou  - one query.. as i was working on a PoC to convert the raw report to the normalized schema, I see that the current table `scan_report` and the new schema (`scan_report_v2`) in this proposal are almost identical except that the new proposed table does not have the `Report` column.
So wanted to understand the common practice followed - would it be OK to re-use the original `scan_report` table itself instead of creating a new table again. IMO, we can re-use the existing table. This way we can allow the following:
* Allow the existing functionality and schema to co-exist with the new ad-hoc query functionality that will be introduced until we switch over completely to the new functionality.
* Reduce the amount of code change - all through the various layers right up to the REST APIs, we would not need to change the name of the table
* Avoid complex queries and data management - copying the content from existing `scan_report` to the new `scan_report_v2`, deleting and cleanup.

Let me know your views

2021-01-04 11:10 UTC, danielpacak requested changes
:wave: @prahaladdarkin I left a few comments to tidy up this proposal and align it with the actual Go code.

2021-01-04 11:10 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +As can be seen above the `Report` data structure no longer holds a JSON blob for the entire report. Each record is represented by the `VulnerabilityRecord` structure shown below and would be stored i
I think we should clarify that we still use the `scan_report` table and associate it with zero to many `vulnerability_records` through the `report_vulnerability_record` junction table. In the current description we are mixing reports with vulnerability records / properties.

2021-01-04 11:10 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +`select count(1) from vulnerability_record where CVEID = '<CVE_ID>'`
```suggestion
```sql
select count(1) from vulnerability_record where cve_id = '<CVE_ID>'`
```

2021-01-04 11:10 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +`select count(1) from vulnerability_record where CVEID = '<CVE_ID>'`
Maybe it's worth mentioning that this query will return CVEs from all registered scanners. Not the default system-wide scanner or the one set at the project level

2021-01-04 11:10 UTC, danielpacak commented on proposals/new/common_vulnerability_schema_proposal.md
> +                                          inner join scan_report sr on rvr.report_uuid = sr.uuid and sr.uuid in (select uuid from scan_report sr inner join
Can we just extend the outer WHERE predicate instead of using embedded SELECT statement?
I think this will be more readable. Also we can use sql syntax to markdown and fix indentation for this example.

2021-01-06 11:06 UTC, prahaladdarkin reviewed
Done. Incorporated all review comments and resolved outstanding conversations.

2021-01-06 11:06 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +                                          inner join scan_report sr on rvr.report_uuid = sr.uuid and sr.uuid in (select uuid from scan_report sr inner join
Done

2021-01-06 11:06 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +Additionally, Garbage collection process may have to be modified to clean up vulnerability data for garbage collected images
Done

2021-01-06 11:06 UTC, prahaladdarkin commented on proposals/new/common_vulnerability_schema_proposal.md
> +For e.g., a certain project within Harbor would require that all it's images have packages with the MIT license. The presence of a GPL packages within the container image would trigger a non-complian
Done

2021-01-07 12:53 UTC, danielpacak approved these changes

2021-01-08 07:32 UTC, steven-zou approved these changes
The feature will be delivered in V2.2.

2021-05-25 01:02 UTC, merged