Add subproject maintainers to GOVERNANCE
goharbor/community pull request #156
Opened 2021-03-08 20:14 UTC by jonasrosland

This PR will add a section regarding subproject maintainers in Harbor's governance documentation.
The reason for this is to ensure contributors within the project can receive elevated privileges and ownership of parts of the project.

Would love to see your thoughts on this, so please discuss.

As outlined in the governance doc, this change would require a supermajority agreement by all maintainers.

Signed-off-by: jonasrosland <jrosland@vmware.com>

2021-03-08 20:21 UTC, Vad1mo commented
love the idea, because it also outlines a path on how to contribute and grow inside project harbor. 
Would definitely try to onboard some harbor related project under the harbor umbrella.

2021-03-09 07:11 UTC, hainingzhang commented
LGTM

2022-12-12 14:15 UTC, Vad1mo approved these changes
Like it

2022-12-12 14:16 UTC, OrlinVasilev commented
@Vad1mo @wy65701436 @stonezdj can we can get this in it's kinda suuuuper old and with the new active sub-projects we need it 100%

2022-12-14 07:56 UTC, OrlinVasilev approved these changes
lgtm

2024-05-28 07:59 UTC, Vad1mo commented
@goharbor/all-maintainers can we come to an agreeement here?

2024-06-06 10:56 UTC, OrlinVasilev approved these changes

2024-07-30 06:21 UTC, OrlinVasilev commented
@yanji09 @wy65701436 please approve!

2024-08-06 06:16 UTC, wy65701436 commented
Regarding the subproject of Harbor, I believe it is not just a matter of defining roles. We should provide a comprehensive definition of a subproject, which should include:

1. What is a subproject of Harbor? What criteria should be considered whether a project is to be accepted as a subproject? and How?
2. How do we measure the quality and release standards of a subproject?
3. What is the withdrawal mechanism for a subproject? For instance, in the case of Harbor Operator, how do we assess the contribution of a maintainer if the subproject is decided to be deprecated?

Introducing a new role could be beneficial for the community, but we need to establish a clear process for managing subprojects, which we currently lack.

2024-08-07 10:30 UTC, wy65701436 commented
Before introducing new role, we probably need to clean up the subproject firstly, there are some of them are super inactive.

2024-08-12 14:45 UTC, thcdrt approved these changes

2024-08-13 08:23 UTC, wy65701436 requested changes
/hold for discussion

2026-07-07 14:46 UTC, bupd commented
closing this in favor of #290

2026-07-07 14:46 UTC, OrlinVasilev commented
https://github.com/goharbor/community/pull/290 supersedes this one so let's close this one!

2026-07-07 14:47 UTC, closed without merging