Fix minor typo in link to holyhope's GitHub
goharbor/community pull request #170
Opened 2021-07-20 21:33 UTC by tianon

Looks like this was missed in https://github.com/goharbor/community/pull/127 and causes the link to lead to https://github.com/goharbor/community/blob/master/github.com/holyhope instead of https://github.com/holyhope.

2021-08-19 19:16 UTC, tianon commented
(I've just rebased again to make sure this is up-to-date :innocent:)

2021-09-15 02:23 UTC, steven-zou approved these changes
LGTM

2021-09-15 02:24 UTC, wy65701436 approved these changes
lgtm

2021-12-09 07:25 UTC, yanji09 approved these changes
LGTM

2021-12-09 07:40 UTC, Vad1mo approved these changes

2021-12-15 21:18 UTC, tianon commented
(Pushed a rebase and some extra minor whitespace consistency adjustments)

2021-12-20 06:33 UTC, yanji09 submitted a review, later dismissed

2022-02-22 11:31 UTC, OrlinVasilev approved these changes
lets merge :)

2022-02-22 11:34 UTC, Vad1mo requested changes
@OrlinVasilev can you change **56K.Cloud** -> **8gears**

2022-02-22 11:36 UTC, Vad1mo approved these changes

2022-02-22 11:39 UTC, OrlinVasilev commented on MAINTAINERS.md
> +| Vadim Bauer | [Vad1mo](https://github.com/Vad1mo) | [56K.Cloud](https://container-registry.com) |
instead of [56K.Cloud] should be [8gears]
```suggestion
| Vadim Bauer | [Vad1mo](https://github.com/Vad1mo) | [8gears](https://container-registry.com) |
```

2022-02-22 11:41 UTC, OrlinVasilev commented
@tianon

2022-02-23 07:30 UTC, OrlinVasilev approved these changes
LGTM

2022-02-23 07:31 UTC, OrlinVasilev commented
@Vad1mo @wy65701436 @steven-zou  please check and approve ! :)

2022-02-23 07:39 UTC, yanji09 approved these changes
LGTM

2022-05-24 11:31 UTC, Vad1mo approved these changes

2022-05-25 07:43 UTC, OrlinVasilev approved these changes
lgtm

2022-05-26 08:37 UTC, yanji09 approved these changes

2022-06-07 21:47 UTC, tianon commented
Superseded by https://github.com/goharbor/community/pull/194

2022-06-07 21:47 UTC, closed without merging