add proposal cosign integration
goharbor/community pull request #172
Opened 2021-07-27 15:56 UTC by wy65701436

The proposal is for cosign and harbor integration story

Signed-off-by: Wang Yan <wangyan@vmware.com>

2021-07-27 18:16 UTC, dlorenc commented
This is awesome and I would love to help out anyway possible! (I'm a maintainer on cosign)

2021-07-30 00:29 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> + digest varchar(1024),
is this column needed?  it's a dup of artifact.digest?

2021-07-30 00:38 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +         "icon":"sha256:0048162a053eef4d4ce3fe7518615bef084403614f8bca43b40ae2e762e11e06",
I may need to refresh my memory about this but do all the icons stored as blobs now, even the preset ones like container images?

2021-07-30 00:39 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +GET /api/v2.0/projects/library/repositories/hello-world/artifacts
Will need to add a querystring for accessories?

2021-07-30 00:42 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +DELETE /api/v2.0/projects/library/repositories/hello-world/artifacts/sha256:1b26826f602946860c279fce658f31050cff2c596583af237d971f4629b57792/accessory?type=signature.cosign&digtest=sha256:94788818ad9
what if the `sha256:94788818ad901025c81f8696f3ee61619526b963b7dc36435ac284f4497aa7cb` is not a accessory of `sha256:1b26826f602946860c279fce658f31050cff2c596583af237d971f4629b57792`?

Do you wanna support both digest and artifact_id when managing an accessory?

2021-07-30 00:47 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +    2. Replication the signature to the target Harbor, then the target Harbor will build the reference.
Since you introduced the `accessory` abstraction layer you should describe the replication scenario in `accessory` terms.

For simplicity if possible IMO all accessories should be replicated considering artifact+accessories is one entity.

What if the target Harbor does not set to `cosign` mode?  I think in that case the signature should not be replicated?

2021-07-30 00:48 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +#### Tag Retention
I don't think this is needed, this is an enhancement to tag retention policy that is out of the scope of cosign integration.

2021-07-30 00:54 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +    - Cosign: If user sign an image with cosign, unless user removes the signature from the artifact, the image will be acted as signed.
So we wanna support notary and cosign at the same time?

2021-07-30 00:57 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +type PublicKey crypto.PublicKey
What is the `PublicKey` related stuff?

2021-07-30 00:58 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +### Request Artifact Accessory
I think we need a section for API change, note that we also need to determine what to do with the existing APIs:
Do we list accessories in GET /artifacts API?
What about DELETE ...

2021-07-30 00:59 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +Cosign can sign a multi-platform `Index`,  but the signature is attached to the index digest. Should we see all the references are signed?
It's hard to handle that when you check the signature in a pull command?

2021-07-30 01:02 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> + artifact_id int,
I feel seeing accessory as an artifact make things more complicated in the API to handle artifacts you need to add a lot of `if` statements b/c accessories are different from regular artifacts.

2021-07-30 01:02 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +2. Cosign can specify the signature repository, do we support it?
Need more context about `signature repository`

2021-07-30 01:03 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +3. Can the signature be added/removed tag or label like other artifact?
It's something to think about for all accessories, see my comment in the table schema for accessory.

2021-07-30 01:05 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +Do we need to support this scenario?
We need to extract the blob to support it right?  If the answer is yes, I suggest not.

2021-07-30 01:08 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +Cosign's model of "appending" signatures won't work for multiple signatures.
Do you mean if a repository is immutable in Harbor you can't push any signatures?

2021-07-30 01:10 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +```json
need more context about this JSON.

2021-07-30 01:11 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +Solution: For GC, the untagged artifact means that one artifact without any tag and are not an accessory.
Then you'll need to make sure the accessory table is in sync, which can be messy to handle.

2021-07-30 13:51 UTC, ncdc reviewed
Thanks for writing this up!

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +    PublicKeyes(ctx context.Context)  ([]PublicKey, error)
```suggestion
    PublicKeys(ctx context.Context)  ([]PublicKey, error)
```

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +      Read all the public key from system.
Do you want this at the system level, or per repository, or maybe both?

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +    - Cosign: If user sign an image with cosign, unless user removes the signature from the artifact, the image will be acted as signed.
I think this makes sense.

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +2. Cosign can specify the signature repository, do we support it?
I believe this is a client-side option only and wouldn't affect the server-side aspects of Harbor?

See https://github.com/sigstore/cosign#specifying-registry for info on what this does.

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +Cosign can sign a multi-platform `Index`,  but the signature is attached to the index digest. Should we see all the references are signed?
I think it makes sense to check that any content you're using as a consumer is signed - i.e. the manifest list (index) and any arch-specific content too.

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +Cosign's model of "appending" signatures won't work for multiple signatures.
You'd be able to push an initial signature manifest, but not any additional signatures.

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +1.  Do not manage Public keys in Harbor side.
Is this a future goal?

2021-07-30 13:51 UTC, ncdc commented on proposals/new/cosign-integration.md
> +7.  As a system & project admin, I can set the content trust policy to block the un-signed artifact pulling.
Without storing public keys, Harbor won't be able to verify the signatures. Would you allow a user to pull an image with a signature when Harbor can't tell if the signature is valid or not?

2021-07-30 14:08 UTC, ncdc commented on proposals/new/cosign-integration.md
> +1. Cosign attaches signature to digest by default, should we apply the signature to all tags of an artifact?
I wouldn't do this. The signature was created for an image with a specific digest (potentially associated with a specific tag at a point in time).

2021-07-30 16:15 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +1. Cosign attaches signature to digest by default, should we apply the signature to all tags of an artifact?
He means the case where different tags associate with one digest.

2021-07-30 16:17 UTC, ncdc commented on proposals/new/cosign-integration.md
> +1. Cosign attaches signature to digest by default, should we apply the signature to all tags of an artifact?
Oh, thanks for the clarification. In that case, I would say yes, display the signature for all tags pointing to the same digest.

2021-07-30 16:21 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +7.  As a system & project admin, I can set the content trust policy to block the un-signed artifact pulling.
Valid or not depends on whether a client chooses to trust the public key or not.

This policy may only check if the signature exists, with the cosign model whether the client should trust it or not is beyond the scope of Harbor.

2021-07-30 16:21 UTC, reasonerjt commented on proposals/new/cosign-integration.md
> +1.  Do not manage Public keys in Harbor side.
Not likely unless tool chain supports push a public key as OCI artifacts.

2021-07-30 16:25 UTC, ncdc commented on proposals/new/cosign-integration.md
> +7.  As a system & project admin, I can set the content trust policy to block the un-signed artifact pulling.
I think it could go either way. Harbor could block if no signature exists and allow if any signature exists.

It could also go further and block if it can't verify the signature. It mostly depends on if we want to require public keys to be uploaded to Harbor so Harbor can verify.

For a first step (and possibly only), we can go with the first approach (Harbor doesn't verify signatures because it doesn't know about public keys).

2021-07-30 16:25 UTC, ncdc commented on proposals/new/cosign-integration.md
> +1.  Do not manage Public keys in Harbor side.
What about a Harbor API for it?

2021-07-30 16:26 UTC, ncdc commented on proposals/new/cosign-integration.md
> +1.  Do not manage Public keys in Harbor side.
Or pubkeys as artifacts could work too

2021-08-09 09:11 UTC, steven-zou commented on proposals/new/cosign-integration.md
> + digest varchar(1024),
+1

2021-08-09 09:27 UTC, steven-zou reviewed
It's cool.

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +    PublicKeyes(ctx context.Context)  ([]PublicKey, error)
What's the use case of this method?

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +    2. Replication the signature to the target Harbor, then the target Harbor will build the reference.
If the root artifact is successfully replicated and the signature artifact replication is failed, is that counted as a success or a failure?

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +2. Cosign can specify the signature repository, do we support it?
For integration with Harbor, living in the same repository seems much better and simpler.

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +3. Can the signature be added/removed tag or label like other artifact?
IMO, as it's an accessory of the root artifacts, it seems there are no use cases to require treating accessory artifacts as general ones。 They're just additional things of the root artifacts.

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +Do we need to support this scenario?
-1.

Conflict with the `To-be-discussed item 1?

2021-08-09 09:27 UTC, steven-zou commented on proposals/new/cosign-integration.md
> +![Build Reference](../images/cosign/build_reference.png)
Leverage the current metadata extracting processor framework?

2021-08-11 00:01 UTC, renmaosheng commented on proposals/new/cosign-integration.md
> +4.  Do not support cosign copy(cosign pushes the signature firstly to the destination, and then the artifact, Harbor cannot build the reference.)
the description is already in the non-goal section, we don't need to add the " Do not" in the sub clause.

2021-08-12 07:18 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +    2. Replication the signature to the target Harbor, then the target Harbor will build the reference.
we can assume that the transation of repliation should contain artifact and signature, and it's failure and the repliated artifact should be removed from the target.

2021-08-12 10:07 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +         "icon":"sha256:0048162a053eef4d4ce3fe7518615bef084403614f8bca43b40ae2e762e11e06",
for the cosign scenario, we can add a default icon in Harbor.

2021-08-12 10:08 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +type PublicKey crypto.PublicKey
Just for further design.

2021-08-12 10:10 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +2. Cosign can specify the signature repository, do we support it?
to support it, it will involve the permission things(AZ).

2021-08-12 10:12 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +Cosign's model of "appending" signatures won't work for multiple signatures.
All the signatures shares one tag name, if the immutable enabled, the following push will be rejected.

2021-08-12 10:13 UTC, wy65701436 commented on proposals/new/cosign-integration.md
> +      Read all the public key from system.
it's a draft design and for the phase 2. But, I suppose it's at the system level.

2021-08-16 17:27 UTC, rszumlakowski reviewed
Does there need to be a user story to confirm that end users will be able to see images with Cosign signatures in the Harbor User Interface?

Something like:

> As a project admin & user, I can see which tags for an artifact have valid cosign signatures

2021-08-25 13:47 UTC, tianon commented
The biggest concern I have with this proposal right now is that the "accessory" that's defined here is very similar to the references work that's happening in the OCI right now (for example https://github.com/opencontainers/tob/issues/96, which has a lot of links to other discussions too).

I'd hate to see Harbor implement something that's very close to something the OCI eventually ratifies, but specific to `cosign` and not quite matching the OCI implementation (creating the need for a migration process for both Harbor and the users of it, assuming the thing that gets ratified is compatible enough to be something we could migrate users to directly).

2021-08-25 13:58 UTC, dlorenc commented
I don't really have a preference either way on waiting, but I don't think it's safe to assume the OCI is actually close to ratifying anything. That link is to a draft proposal that's been open since April and still hasn't been submitted as a real proposal for a vote.

After that vote, the WG would then need to actually start, design and prototype different options. Then the spec changes would need to get written, debated and approved. Then enough registries would need to implement those changes for it to be safe for clients to rely on them. 

I'm (pessimistically) guessing it's going to be mid to late 2022 at the earliest before there's enough widespread adoption of the new changes for clients to rely on them.

The cosign spec is defined here, with a goal of working with existing registries; https://github.com/sigstore/cosign/blob/main/specs/SIGNATURE_SPEC.md and is already implemented by a few other clients so it's not really cosign specific.

2021-08-25 14:01 UTC, tianon commented
Thanks @dlorenc for providing your thoughts -- I guess that changes the question a little bit for me then. :smile:

Why does adding "cosign support" to Harbor require creating this special "accessory" type?  Is the goal of doing so to make it more usable/useful to end users, or is there a deeper reason?

2021-08-25 14:22 UTC, dlorenc commented
> Why does adding "cosign support" to Harbor require creating this special "accessory" type? Is the goal of doing so to make it more usable/useful to end users,

My understanding is that this is for extra features, like UI integration and policy support on top of the signatures. Basic sign/verify/upload/download operations all work with harbor out of the box.

2021-08-25 16:28 UTC, wy65701436 commented
> Thanks @dlorenc for providing your thoughts -- I guess that changes the question a little bit for me then. 😄
> 
> Why does adding "cosign support" to Harbor require creating this special "accessory" type? Is the goal of doing so to make it more usable/useful to end users, or is there a deeper reason?

To add the `accessory` is just to let Habor knows the `relationship` of artifact and its signature. Otherwise, from the perspective of Harbor, the cosign signature is just another irrelevant artifact. 

Through the `relationship`, Harbor can treat the artifact and its signature as a whloe, and then determine the behavior of GC/Remove/Replication/....

2021-09-16 00:29 UTC, SteveLasker commented
JFYI, the [ORAS Artifacts Draft Specification](https://github.com/oras-project/artifacts-spec/) has been [released](https://github.com/oras-project/artifacts-spec/releases/tag/1.0.0-draft.1). It generalizes the way references can be pushed, discovered and pulled, enabling a standard across all distribution-spec based registries:

2022-02-11 04:54 UTC, chlins approved these changes
lgtm

2022-02-11 06:22 UTC, stonezdj approved these changes

2022-02-11 06:52 UTC, Vad1mo requested changes

2022-02-11 06:52 UTC, Vad1mo commented on proposals/new/accessory.md
> +The proposal is to introduce an abstract definition -- accessory -- to enable Harbor to extend the capabilities for storing artifact with additional stuff.
@tianon you as a native speaker, do you think the term **[accessory](https://www.merriam-webster.com/dictionary/accessory)** is correct here or would you use a better suited term?

I would like to critically question the "term", as it will stick on forever and generation of Harbor developers and users would need lookup the manual and the code just to understand what it means. 

IMHO an artifact **artifact attachment** or **attachment** would be a better suited term because: 

1. It is a common and well know term for an object that can be (optionally) attached to another object. It is known to many user and developers from email, documents and files. 
2. A good word that denotes the common use correctly will save thousand hours of time for many many users and developers.

2022-02-11 07:08 UTC, steven-zou approved these changes
LGTM

2022-03-10 02:56 UTC, wy65701436 commented on proposals/new/accessory.md
> +The proposal is to introduce an abstract definition -- accessory -- to enable Harbor to extend the capabilities for storing artifact with additional stuff.
thanks @Vad1mo and @tianon, firstly, we'd like to extend the `accessory` into more cases, like SBoM, Nydus(converted images).

I know the OCI or Oras community uses the `attachement` to describe the linkage of subject manifest and its things. IMO, in Harbor, I'd like to use different term to descirbe, we can say, the same thing to avoid confusion. A typical example is `label`,  in Harbor we have this term to help user to filter artifact. However, in docker community, labels are an key-value pair.

And since we've reached the RC stage and all the source code has been merged, we have to draw an conclusion soon.

2022-03-21 13:19 UTC, merged