feat: integrate cloud event for webhook
goharbor/community pull request #213
Opened 2023-02-09 07:15 UTC by chlins

Closes: https://github.com/goharbor/harbor/issues/17748

Signed-off-by: chlins <chenyuzh@vmware.com>

2023-02-09 07:17 UTC, chlins commented
@goharbor/all-maintainers Please help to review this proposal, thanks!

2023-02-22 11:47 UTC, Vad1mo requested changes
The pyload format name should be correctly set to "CloudEvents"

2023-02-28 03:02 UTC, chlins commented on proposals/new/cloudevent.md
> +# Proposal: Support Cloud Event For Webhook
Thanks, updated.

2023-03-14 08:43 UTC, wy65701436 approved these changes
lgtm

2023-03-14 09:00 UTC, AllForNothing approved these changes
lgtm

2023-03-14 09:10 UTC, stonezdj approved these changes

2023-03-14 09:19 UTC, chlins commented
@Vad1mo Hi, the comments have been resolved, please help to review again, thanks.

2023-03-20 08:07 UTC, Vad1mo approved these changes
🎉

2023-03-20 08:07 UTC, merged

2023-03-21 06:40 UTC, OrlinVasilev commented
That's fantastic folks!!!!!!!!