Add robot-full-permission proposal
goharbor/community pull request #232
Opened 2023-09-07 04:51 UTC by AllForNothing

Original issue https://github.com/goharbor/harbor/issues/8723

1.Expose all the robot permissions on the Harbor UI for users to choose freely

2023-11-01 08:14 UTC, Vad1mo requested changes
This looks good so far.
I Have the fear that this feature will overwhelm a typical Harbor day to day user and use case.
As a suggestion, can we break up this UI change into two parts?

1.  Keep the current selection with the typical dropdown is present where the use can select the common permission. 

2. Add an expert mode where the user is presented with the matrix and can select. individual permissions. What is currently displayed in the screenshots.

2023-11-01 08:31 UTC, AllForNothing commented
@Vad1mo The screenshots are out of date, I will update them later.
I've refactored it based on the designer's suggestions and now it looks similar to your suggestions. And I will demo the new UI in today's community meeting.

2023-11-01 12:32 UTC, OrlinVasilev commented
that would be so cool with the expert mode!!!

2023-11-02 17:01 UTC, wy65701436 approved these changes
lgtm

2023-11-17 09:32 UTC, YangJiao0817 requested changes

2023-11-17 09:32 UTC, YangJiao0817 commented on proposals/new/robot-full-permission.md
> +115. put    /users/{user_id}/cli_secret                     resource:  user     |   action: update
The user API should be disabled。

2023-12-12 08:33 UTC, YangJiao0817 approved these changes

2023-12-12 08:34 UTC, merged