Enhance audit log
goharbor/community pull request #253
Opened 2024-11-28 02:18 UTC by stonezdj

2024-11-28 05:02 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +With the above event type, the Harbor administrator can trace the user's behavior in the system, and know who has done what in the system, and when it happened, and the source of the request. make th
I suggest we first clarify "audit log".  Is it only for tracing "user triggered" event?
For example if a scan is triggered by schedule, should it be traced as "audit log"?

2024-11-28 05:04 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +    IPAddress    string 
As discussed in another PR.  The IP address can be misleading in many ways, are you sure we wanna add it?

2024-11-28 05:04 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +    OperationResult string
Is it string or bool?

2024-11-28 05:06 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +    RequestPayload string
IMO we should add a translation layer to translate the request body to event-specific parameters.

2024-11-28 05:07 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +Proposal: Enhance Audit Log
Let's highilght in the title that this is WIP or draft, if it's not ready for review by the community.

2024-11-28 05:39 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +
1. I think we also need to explain supporting different backends for storing audit log, and how to make it possible to send to other backends like open-telemetry?
2. Are there any consideration in Querying the audit-log?  Are there any changes needed in the API?   Will we only support querying audit-log in Harbor API when the backend of audit-log is DB?

2024-11-28 06:20 UTC, Vad1mo commented
This proposal not only introduces a new auditlogo but also add much more events.

- The volume of transactions that the new system can cause in a high pull/push environments. One crucial part of the enhanced auditlog should be the decoupling of event producer action and  event writing.  In other words, an artifact pull/push should not be affects by the eventlog.

- The Database is currently the bottelneck of Harbor, especially on large installations, with many artifacts, polcies, voulnerability data. Reducing the pressure on the Database should be priority in the new auditlogs. Adding Redis here will not improve the situation, unless we use/implement a Write-Back Caching strategy.

I suggest also making the auditlog plugable, meaning that in the future it would be possible to add other types of backends apart from postgres, like opentelemtry or loki..

2024-11-28 06:36 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +    IPAddress    string 
should we record the ip address? As I recall that we have concern the ip may not reflect the truth.

2024-11-28 06:48 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +		if enableAudit {
do we record non-200 actions? like someone attempted to access a forbidden resource or login failed.

2024-11-28 06:57 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +
I think, we also need to consider that the Queryable. Like, an administrator want to filter out all logs where user A performed action B from source C between the dates D and E.

2024-11-28 06:59 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +type AuditLog struct {
I'm not sure how to ensure immutability from a database perspective.

2024-12-11 08:40 UTC, stonezdj commented
> This proposal not only introduces a new auditlogo but also add much more events.
> 
> * The volume of transactions that the new system can cause in a high pull/push environments. One crucial part of the enhanced auditlog should be the decoupling of event producer action and  event writing.  In other words, an artifact pull/push should not be affects by the eventlog.
> * The Database is currently the bottelneck of Harbor, especially on large installations, with many artifacts, polcies, voulnerability data. Reducing the pressure on the Database should be priority in the new auditlogs. Adding Redis here will not improve the situation, unless we use/implement a Write-Back Caching strategy.
> 
> I suggest also making the auditlog plugable, meaning that in the future it would be possible to add other types of backends apart from postgres, like opentelemtry or loki..
> 
> I am looking into few options and [Unlogged tables ](https://pganalyze.com/blog/5mins-postgres-unlogged-tables) directly or in combination with stored procedures can provide a huge improvement in write performance.

Previous audit log has the log forward option, it can avoid log in the database
![Screenshot 2024-12-11 at 16 39 55](https://github.com/user-attachments/assets/a73824eb-3077-42bd-941e-1865034998f9)

2024-12-11 08:42 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +With the above event type, the Harbor administrator can trace the user's behavior in the system, and know who has done what in the system, and when it happened, and the source of the request. make th
correct

2024-12-11 08:46 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +
We can use the q.Query parameter to extend the queryable on audit log.

2024-12-11 09:17 UTC, Vad1mo commented
> Previous audit log has the log forward option, it can avoid log in the database

The problem with the existing approach is that when this is enabled. Audit logs aren't displayed in Harbor anymore. All events are forwarded to syslog. 

What I had in mind was had the option to implement a different storage backend instead of the postgres.

2024-12-11 09:18 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +## Schema Change
please also include the audit v2 apis in this proposal.

2024-12-12 05:10 UTC, stonezdj commented
> > Previous audit log has the log forward option, it can avoid log in the database
> 
> The problem with the existing approach is that when this is enabled. Audit logs aren't displayed in Harbor anymore. All events are forwarded to syslog.
> 
> What I had in mind was had the option to implement a different storage backend instead of the postgres.

When you configured forward log to LogInsight or ELK, you should search the audit log in the ELK's query interface.

2024-12-16 07:56 UTC, reasonerjt commented
> The problem with the existing approach is that when this is enabled. Audit logs aren't displayed in Harbor anymore. All events are forwarded to syslog.
> 
> What I had in mind was had the option to implement a different storage backend instead of the postgres.

@Vad1mo This is essentially a query module in Harbor that works with different backends.
The requirement to provide a pluggable query module in Harbor for audit logs should be tracked separately. 
And as Stone has suggested, when the user chooses to store Harbor's audit logs to a 3rd party system, normally he will query the information from the 3rd party system instead from Harbor.

2024-12-17 10:04 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +
Some overall suggestions:
1.  Clearly mention what will be implemented in v2.13
2. Add a few paragraphs to address common issues, like "source IP", support sending audit logs to 3rd party service other than Harbor's DB.

2024-12-18 08:27 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +    Resource     string    `orm:"column(resource)" json:"resource"`
Prefer resource name, some resource has no name, it will be ID.

2024-12-18 09:14 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +The above steps are cumbersome and error-prone when there are too many event types. To simplify the process, we can create a common event metadata and a common event that can handle all events relate
current is used for audit log handler, but it can be subscribed by other handler

2024-12-18 09:30 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +		re := regexp.MustCompile("^/c/log_out$")
`GET /c/log_out` is used to check if it is a logout event.

2024-12-18 09:33 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +create_user, delete_user, update_user
just keep the configuration item as simple as possible

2024-12-18 09:39 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +For each basic event type, we can create a resolver to resolve the common event to the specific event type, such as userResolver, projectResolver, robotResolver, etc.
OK, update it

2024-12-18 09:51 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +		if auditLog != nil && config.AuditLogEnabled(ctx, fmt.Sprintf("%v_%v", auditLog.Operation, auditLog.ResourceType)) {
Because the previous audit_log_disable should apply to the existing audit log implementation, such as image create image delete, it should be check here.

2024-12-18 09:52 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +			event := &commonevent.Metadata{
the function PreCheck() can filter the event before propagating.

2024-12-18 09:53 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +func (c *Metadata) PreCheck(ctx context.Context) (bool, string) {
filter event before propogating

2024-12-30 06:01 UTC, wy65701436 commented on proposals/new/enhance_audit_log.md
> +1. As a Harbor administrator, I want to know who has logged in/logout to the system, so that I can trace the user's behavior in the system.
As discussed, we prefer to do the 1,3 and 4. Please update it accordingly.

2024-12-31 05:19 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +      event_id:
Isn't the event_id and name a dup?  We'll need to transform the response to the label for display either way.

2024-12-31 05:19 UTC, reasonerjt commented on proposals/new/enhance_audit_log.md
> +Add a new API to query the audit log ext event. the API is `/api/v2.0/auditlog-exts`, the user can filter the audit log event by the operation, resource_type, resource, the operation description and
This is trivial but `auditlogs-ext` is better b/c the ext is just a suffix to distinguish it from the old resource.

2025-01-09 08:45 UTC, Vad1mo requested changes

2025-01-09 08:45 UTC, Vad1mo commented on proposals/new/enhance_audit_log.md
> +  /auditlog-exts/events:
what does the **exts** mean in the api? 

Why not make it clear to the user eg as in **auditlog2**

2025-01-14 06:32 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +  /auditlog-exts/events:
It is just a extension of the audit log, add ext suffix.

2025-01-14 06:33 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +    ProjectID    int64     `orm:"column(project_id)" json:"project_id"`
The project id would be empty, the project id is required when querying audit log with project, because audit log can query under project tab.

2025-01-14 06:34 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +
Updated

2025-01-14 06:35 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +    IPAddress    string 
Keep the IPAddress as a reserved column

2025-01-14 06:36 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +    RequestPayload string
payload is a reserved column for future usage.

2025-01-14 06:37 UTC, stonezdj commented on proposals/new/enhance_audit_log.md
> +
Already updated in the proposal

2025-01-14 06:51 UTC, stonezdj commented
> > Previous audit log has the log forward option, it can avoid log in the database
> 
> The problem with the existing approach is that when this is enabled. Audit logs aren't displayed in Harbor anymore. All events are forwarded to syslog.
> 
> What I had in mind was had the option to implement a different storage backend instead of the postgres.

Replace postgres is a big task, we have no bandwidth to handle so far.

2025-02-17 09:39 UTC, chlins approved these changes
lgtm

2025-02-18 03:19 UTC, reasonerjt approved these changes

2025-02-18 03:20 UTC, merged